#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Aki Moto aki.robosys2025@gmail.com
# SPDX-License-Indentifier: BSD-3-Clause

import sys

ans = 0

for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
