#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Aki Moto aki.robosys2025@gmail.com
# SPDX-License-Indentifier: BSD-3-Clause

import sys

def tonom(s):
    try:
        ans += int(s)
    except:
        ans += float(s)

ans = 0

for line in sys.stdin:
    ans += tonom(line)

print(ans)
