#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Aki Moto aki.robosys2025@gmail.com
# SPDX-License-Indentifier: BSD-3-Clause

import sys

def prime_factor(n: int):
    a = []
    i = 2

    while i * i <= n:
        while n % i == 0:
            a.append(i)
            n //= i

        i += 1

    if n > 1:
        a.append(n)

    return a

std = sys.stdin.read().strip()
num = int(std)
ans = prime_factor(num)

print(*ans)
